[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("MoveDraft","EditNote","Restore")]
    [string]$Action,

    [Parameter(Mandatory = $true)]
    [ValidateSet("Preview","Apply")]
    [string]$Mode,

    [string]$SourceDraft,
    [string]$TargetRelativePath,
    [string]$NewContent,
    [string]$NewContentFile,
    [string]$RecoveryFile,
    [string]$ApprovalToken,

    [switch]$Json
)

$ErrorActionPreference = "Stop"

$Container = "orion-vault-broker"
$Payload = "CmltcG9ydCBoYXNobGliCmltcG9ydCBqc29uCmltcG9ydCBvcwppbXBvcnQgc2h1dGlsCmltcG9ydCBzeXMKaW1wb3J0IGRpZmZsaWIKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUsIHRpbWV6b25lCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aCwgUHVyZVBvc2l4UGF0aApmcm9tIHV1aWQgaW1wb3J0IHV1aWQ0CgpWQVVMVCA9IFBhdGgoIi93b3Jrc3BhY2UiKQpJTkJPWCA9IFBhdGgoIi9pbmJveCIpClJFQ09WRVJZID0gUGF0aCgiL3JlY292ZXJ5IikKTUFYX1RFWFRfQ0hBUlMgPSAxMDBfMDAwCgpkZWYgZW1pdChvYmosIGNvZGU9MCk6CiAgICBwcmludChqc29uLmR1bXBzKG9iaiwgZW5zdXJlX2FzY2lpPUZhbHNlKSkKICAgIHJhaXNlIFN5c3RlbUV4aXQoY29kZSkKCmRlZiBzaGFfYnl0ZXMoZGF0YTogYnl0ZXMpIC0+IHN0cjoKICAgIHJldHVybiBoYXNobGliLnNoYTI1NihkYXRhKS5oZXhkaWdlc3QoKQoKZGVmIHNoYV90ZXh0KHRleHQ6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuIHNoYV9ieXRlcyh0ZXh0LmVuY29kZSgidXRmLTgiKSkKCmRlZiBzYWZlX3JlbChyb290OiBQYXRoLCByYXc6IHN0ciwgKiwgbXVzdF9leGlzdD1GYWxzZSwgYWxsb3dfbWlzc2luZ19sZWFmPUZhbHNlKToKICAgIHJhdyA9IChyYXcgb3IgIiIpLnN0cmlwKCkKICAgIGlmIG5vdCByYXcgb3IgIlx4MDAiIGluIHJhdzoKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCJpbnZhbGlkX3JlbGF0aXZlX3BhdGgiKQogICAgbm9ybSA9IHJhdy5yZXBsYWNlKCJcXCIsICIvIikKICAgIHAgPSBQdXJlUG9zaXhQYXRoKG5vcm0pCiAgICBpZiBwLmlzX2Fic29sdXRlKCk6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigiYWJzb2x1dGVfcGF0aF9yZWplY3RlZCIpCiAgICBpZiBhbnkocGFydCBpbiAoIiIsICIuIiwgIi4uIikgZm9yIHBhcnQgaW4gcC5wYXJ0cyk6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigicGF0aF90cmF2ZXJzYWxfcmVqZWN0ZWQiKQogICAgaWYgbm90IHAucGFydHM6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigiaW52YWxpZF9yZWxhdGl2ZV9wYXRoIikKICAgIGNhbmRpZGF0ZSA9IHJvb3Quam9pbnBhdGgoKnAucGFydHMpCgogICAgIyBSZWplY3Qgc3ltbGluayB0cmF2ZXJzYWwgdGhyb3VnaCBhbnkgZXhpc3RpbmcgY29tcG9uZW50LgogICAgY3Vyc29yID0gcm9vdAogICAgZm9yIHBhcnQgaW4gcC5wYXJ0czoKICAgICAgICBjdXJzb3IgPSBjdXJzb3IgLyBwYXJ0CiAgICAgICAgaWYgY3Vyc29yLmV4aXN0cygpIGFuZCBjdXJzb3IuaXNfc3ltbGluaygpOgogICAgICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCJzeW1saW5rX3BhdGhfcmVqZWN0ZWQiKQoKICAgIHJvb3RfcmVhbCA9IHJvb3QucmVzb2x2ZSgpCiAgICBpZiBjYW5kaWRhdGUuZXhpc3RzKCk6CiAgICAgICAgcmVhbCA9IGNhbmRpZGF0ZS5yZXNvbHZlKHN0cmljdD1UcnVlKQogICAgICAgIHRyeToKICAgICAgICAgICAgcmVhbC5yZWxhdGl2ZV90byhyb290X3JlYWwpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigicmVzb2x2ZWRfcGF0aF9vdXRzaWRlX3Jvb3QiKQogICAgZWxzZToKICAgICAgICBwYXJlbnQgPSBjYW5kaWRhdGUucGFyZW50CiAgICAgICAgIyBSZXNvbHZlIHRoZSBuZWFyZXN0IGV4aXN0aW5nIGFuY2VzdG9yLgogICAgICAgIGFuY2VzdG9yID0gcGFyZW50CiAgICAgICAgd2hpbGUgbm90IGFuY2VzdG9yLmV4aXN0cygpIGFuZCBhbmNlc3RvciAhPSByb290OgogICAgICAgICAgICBhbmNlc3RvciA9IGFuY2VzdG9yLnBhcmVudAogICAgICAgIHJlYWxfYW5jZXN0b3IgPSBhbmNlc3Rvci5yZXNvbHZlKHN0cmljdD1UcnVlKQogICAgICAgIHRyeToKICAgICAgICAgICAgcmVhbF9hbmNlc3Rvci5yZWxhdGl2ZV90byhyb290X3JlYWwpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigicmVzb2x2ZWRfcGFyZW50X291dHNpZGVfcm9vdCIpCgogICAgaWYgbXVzdF9leGlzdCBhbmQgbm90IGNhbmRpZGF0ZS5pc19maWxlKCk6CiAgICAgICAgcmFpc2UgRmlsZU5vdEZvdW5kRXJyb3IoInBhdGhfbm90X2ZvdW5kIikKICAgIGlmIG5vdCBhbGxvd19taXNzaW5nX2xlYWYgYW5kIG5vdCBtdXN0X2V4aXN0IGFuZCBub3QgY2FuZGlkYXRlLmV4aXN0cygpOgogICAgICAgIHBhc3MKICAgIHJldHVybiBjYW5kaWRhdGUsIHAuYXNfcG9zaXgoKQoKZGVmIHJlcXVpcmVfbWQocmVsOiBzdHIpOgogICAgaWYgbm90IHJlbC5sb3dlcigpLmVuZHN3aXRoKCIubWQiKToKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCJtYXJrZG93bl9vbmx5IikKCmRlZiByZWFkX3V0ZjgocGF0aDogUGF0aCkgLT4gc3RyOgogICAgZGF0YSA9IHBhdGgucmVhZF9ieXRlcygpCiAgICB0cnk6CiAgICAgICAgcmV0dXJuIGRhdGEuZGVjb2RlKCJ1dGYtOCIpCiAgICBleGNlcHQgVW5pY29kZURlY29kZUVycm9yOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoInV0ZjhfcmVxdWlyZWQiKQoKZGVmIHBsYW5fdG9rZW4ocGxhbjogZGljdCkgLT4gc3RyOgogICAgcGF5bG9hZCA9IGpzb24uZHVtcHMocGxhbiwgc29ydF9rZXlzPVRydWUsIHNlcGFyYXRvcnM9KCIsIiwgIjoiKSwgZW5zdXJlX2FzY2lpPUZhbHNlKQogICAgcmV0dXJuIGhhc2hsaWIuc2hhMjU2KHBheWxvYWQuZW5jb2RlKCJ1dGYtOCIpKS5oZXhkaWdlc3QoKQoKZGVmIHVuaWZpZWQob2xkOiBzdHIsIG5ldzogc3RyLCBvbGRfbmFtZTogc3RyLCBuZXdfbmFtZTogc3RyKSAtPiBzdHI6CiAgICByZXR1cm4gIiIuam9pbihkaWZmbGliLnVuaWZpZWRfZGlmZigKICAgICAgICBvbGQuc3BsaXRsaW5lcyhrZWVwZW5kcz1UcnVlKSwKICAgICAgICBuZXcuc3BsaXRsaW5lcyhrZWVwZW5kcz1UcnVlKSwKICAgICAgICBmcm9tZmlsZT1vbGRfbmFtZSwKICAgICAgICB0b2ZpbGU9bmV3X25hbWUsCiAgICAgICAgbGluZXRlcm09IlxuIiwKICAgICkpCgpkZWYgcmVjb3Zlcnlfc25hcHNob3QoKiwgYWN0aW9uOiBzdHIsIHRhcmdldF9yZWw6IHN0ciwgc291cmNlX2J5dGVzOiBieXRlcywgZXh0cmE9Tm9uZSk6CiAgICBSRUNPVkVSWS5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBzdGFtcCA9IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnN0cmZ0aW1lKCIlWSVtJWRUJUglTSVTWiIpCiAgICByaWQgPSBmIntzdGFtcH0te3V1aWQ0KCkuaGV4WzoxMF19IgogICAgZW50cnkgPSBSRUNPVkVSWSAvIHJpZAogICAgZW50cnkubWtkaXIobW9kZT0wbzcwMCkKICAgIGJhY2t1cCA9IGVudHJ5IC8gImJhY2t1cC5tZCIKICAgIGJhY2t1cC53cml0ZV9ieXRlcyhzb3VyY2VfYnl0ZXMpCiAgICBtZXRhID0gewogICAgICAgICJyZWNvdmVyeV9pZCI6IHJpZCwKICAgICAgICAiYWN0aW9uIjogYWN0aW9uLAogICAgICAgICJ0YXJnZXRfcmVsYXRpdmVfcGF0aCI6IHRhcmdldF9yZWwsCiAgICAgICAgImJhY2t1cF9zaGEyNTYiOiBzaGFfYnl0ZXMoc291cmNlX2J5dGVzKSwKICAgICAgICAiY3JlYXRlZF9hdCI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnJlcGxhY2UobWljcm9zZWNvbmQ9MCkuaXNvZm9ybWF0KCksCiAgICB9CiAgICBpZiBleHRyYToKICAgICAgICBtZXRhLnVwZGF0ZShleHRyYSkKICAgIChlbnRyeSAvICJtZXRhZGF0YS5qc29uIikud3JpdGVfdGV4dCgKICAgICAgICBqc29uLmR1bXBzKG1ldGEsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50PTIpICsgIlxuIiwgZW5jb2Rpbmc9InV0Zi04IgogICAgKQogICAgcmV0dXJuIHJpZCwgZiJ7cmlkfS9iYWNrdXAubWQiCgpkZWYgcGFyc2VfcmVxdWVzdCgpOgogICAgcmF3ID0gc3lzLnN0ZGluLnJlYWQoKQogICAgdHJ5OgogICAgICAgIHJlcSA9IGpzb24ubG9hZHMocmF3KQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6ImludmFsaWRfcmVxdWVzdF9qc29uIn0sIDIpCiAgICBpZiBub3QgaXNpbnN0YW5jZShyZXEsIGRpY3QpOgogICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoicmVxdWVzdF9tdXN0X2JlX29iamVjdCJ9LCAyKQogICAgcmV0dXJuIHJlcQoKcmVxID0gcGFyc2VfcmVxdWVzdCgpCmFjdGlvbiA9IHN0cihyZXEuZ2V0KCJhY3Rpb24iKSBvciAiIikuc3RyaXAoKS5sb3dlcigpCm1vZGUgPSBzdHIocmVxLmdldCgibW9kZSIpIG9yICIiKS5zdHJpcCgpLmxvd2VyKCkKYXBwcm92YWwgPSBzdHIocmVxLmdldCgiYXBwcm92YWxfdG9rZW4iKSBvciAiIikuc3RyaXAoKQoKaWYgYWN0aW9uIG5vdCBpbiAoIm1vdmVfZHJhZnQiLCAiZWRpdF9ub3RlIiwgInJlc3RvcmUiKToKICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoiaW52YWxpZF9hY3Rpb24ifSwgMykKaWYgbW9kZSBub3QgaW4gKCJwcmV2aWV3IiwgImFwcGx5Iik6CiAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6ImludmFsaWRfbW9kZSJ9LCA0KQoKZm9yIHJvb3QsIG5hbWUgaW4gKChWQVVMVCwidmF1bHQiKSwoSU5CT1gsImluYm94IiksKFJFQ09WRVJZLCJyZWNvdmVyeSIpKToKICAgIGlmIG5vdCByb290LmlzX2RpcigpOgogICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjpmIntuYW1lfV9yb290X21pc3NpbmcifSwgNSkKCnRyeToKICAgIGlmIGFjdGlvbiA9PSAibW92ZV9kcmFmdCI6CiAgICAgICAgc291cmNlX3JhdyA9IHN0cihyZXEuZ2V0KCJzb3VyY2VfZHJhZnQiKSBvciAiIikKICAgICAgICB0YXJnZXRfcmF3ID0gc3RyKHJlcS5nZXQoInRhcmdldF9yZWxhdGl2ZV9wYXRoIikgb3IgIiIpCiAgICAgICAgc291cmNlLCBzb3VyY2VfcmVsID0gc2FmZV9yZWwoSU5CT1gsIHNvdXJjZV9yYXcsIG11c3RfZXhpc3Q9VHJ1ZSkKICAgICAgICB0YXJnZXQsIHRhcmdldF9yZWwgPSBzYWZlX3JlbChWQVVMVCwgdGFyZ2V0X3JhdywgYWxsb3dfbWlzc2luZ19sZWFmPVRydWUpCiAgICAgICAgcmVxdWlyZV9tZChzb3VyY2VfcmVsKQogICAgICAgIHJlcXVpcmVfbWQodGFyZ2V0X3JlbCkKICAgICAgICBpZiB0YXJnZXQuZXhpc3RzKCk6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoidGFyZ2V0X2FscmVhZHlfZXhpc3RzIiwidGFyZ2V0X3JlbGF0aXZlX3BhdGgiOnRhcmdldF9yZWx9LCAxMCkKICAgICAgICBpZiBzb3VyY2UuaXNfc3ltbGluaygpOgogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6InN5bWxpbmtfc291cmNlX3JlamVjdGVkIn0sIDExKQoKICAgICAgICBzcmNfYnl0ZXMgPSBzb3VyY2UucmVhZF9ieXRlcygpCiAgICAgICAgc3JjX3RleHQgPSByZWFkX3V0Zjgoc291cmNlKQogICAgICAgIGlmICJvcmlvbl9kcmFmdDogdHJ1ZSIgbm90IGluIHNyY190ZXh0IG9yICJzdGF0dXM6IGRyYWZ0IiBub3QgaW4gc3JjX3RleHQ6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoic291cmNlX2lzX25vdF9vcmlvbl9kcmFmdCJ9LCAxMikKCiAgICAgICAgcGxhbiA9IHsKICAgICAgICAgICAgImFjdGlvbiI6Im1vdmVfZHJhZnQiLAogICAgICAgICAgICAic291cmNlX2RyYWZ0Ijpzb3VyY2VfcmVsLAogICAgICAgICAgICAidGFyZ2V0X3JlbGF0aXZlX3BhdGgiOnRhcmdldF9yZWwsCiAgICAgICAgICAgICJzb3VyY2Vfc2hhMjU2IjpzaGFfYnl0ZXMoc3JjX2J5dGVzKSwKICAgICAgICAgICAgInRhcmdldF9zdGF0ZSI6ImFic2VudCIsCiAgICAgICAgfQogICAgICAgIHRva2VuID0gcGxhbl90b2tlbihwbGFuKQogICAgICAgIGRpZmYgPSB1bmlmaWVkKCIiLCBzcmNfdGV4dCwgIi9kZXYvbnVsbCIsIGYidmF1bHQve3RhcmdldF9yZWx9IikKCiAgICAgICAgaWYgbW9kZSA9PSAicHJldmlldyI6CiAgICAgICAgICAgIGVtaXQoewogICAgICAgICAgICAgICAgInN0YXR1cyI6Im9rIiwKICAgICAgICAgICAgICAgICJtb2RlIjoicHJldmlldyIsCiAgICAgICAgICAgICAgICAiYWN0aW9uIjoibW92ZV9kcmFmdCIsCiAgICAgICAgICAgICAgICAic291cmNlX2RyYWZ0Ijpzb3VyY2VfcmVsLAogICAgICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAgICAgInNvdXJjZV9zaGEyNTYiOnBsYW5bInNvdXJjZV9zaGEyNTYiXSwKICAgICAgICAgICAgICAgICJhcHByb3ZhbF90b2tlbiI6dG9rZW4sCiAgICAgICAgICAgICAgICAiZGlmZiI6ZGlmZiwKICAgICAgICAgICAgfSkKCiAgICAgICAgaWYgYXBwcm92YWwgIT0gdG9rZW46CiAgICAgICAgICAgIGVtaXQoewogICAgICAgICAgICAgICAgInN0YXR1cyI6ImRlbmllZCIsCiAgICAgICAgICAgICAgICAiZXJyb3IiOiJhcHByb3ZhbF90b2tlbl9taXNtYXRjaCIsCiAgICAgICAgICAgICAgICAiYWN0aW9uIjoibW92ZV9kcmFmdCIsCiAgICAgICAgICAgICAgICAidGFyZ2V0X3JlbGF0aXZlX3BhdGgiOnRhcmdldF9yZWwsCiAgICAgICAgICAgIH0sIDIwKQoKICAgICAgICB0YXJnZXQucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgICAgICAjIFJlLWNoZWNrIHN5bWxpbmsgc2FmZXR5IGFmdGVyIG1rZGlyLgogICAgICAgIHNhZmVfcmVsKFZBVUxULCB0YXJnZXRfcmVsLCBhbGxvd19taXNzaW5nX2xlYWY9VHJ1ZSkKICAgICAgICBpZiB0YXJnZXQuZXhpc3RzKCk6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoidGFyZ2V0X2NyZWF0ZWRfc2luY2VfcHJldmlldyJ9LCAyMSkKCiAgICAgICAgcmVjb3ZlcnlfaWQsIHJlY292ZXJ5X2ZpbGUgPSByZWNvdmVyeV9zbmFwc2hvdCgKICAgICAgICAgICAgYWN0aW9uPSJtb3ZlX2RyYWZ0IiwKICAgICAgICAgICAgdGFyZ2V0X3JlbD10YXJnZXRfcmVsLAogICAgICAgICAgICBzb3VyY2VfYnl0ZXM9c3JjX2J5dGVzLAogICAgICAgICAgICBleHRyYT17InNvdXJjZV9kcmFmdCI6c291cmNlX3JlbH0sCiAgICAgICAgKQoKICAgICAgICB3aXRoIHRhcmdldC5vcGVuKCJ4YiIpIGFzIGY6CiAgICAgICAgICAgIGYud3JpdGUoc3JjX2J5dGVzKQogICAgICAgIGlmIHNoYV9ieXRlcyh0YXJnZXQucmVhZF9ieXRlcygpKSAhPSBwbGFuWyJzb3VyY2Vfc2hhMjU2Il06CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHRhcmdldC51bmxpbmsoKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6InRhcmdldF92ZXJpZmljYXRpb25fZmFpbGVkIn0sIDIyKQoKICAgICAgICBzb3VyY2UudW5saW5rKCkKICAgICAgICBlbWl0KHsKICAgICAgICAgICAgInN0YXR1cyI6Im9rIiwKICAgICAgICAgICAgIm1vZGUiOiJhcHBseSIsCiAgICAgICAgICAgICJhY3Rpb24iOiJtb3ZlX2RyYWZ0IiwKICAgICAgICAgICAgInNvdXJjZV9kcmFmdCI6c291cmNlX3JlbCwKICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAicmVzdWx0X3NoYTI1NiI6cGxhblsic291cmNlX3NoYTI1NiJdLAogICAgICAgICAgICAicmVjb3ZlcnlfaWQiOnJlY292ZXJ5X2lkLAogICAgICAgICAgICAicmVjb3ZlcnlfZmlsZSI6cmVjb3ZlcnlfZmlsZSwKICAgICAgICB9KQoKICAgIGVsaWYgYWN0aW9uID09ICJlZGl0X25vdGUiOgogICAgICAgIHRhcmdldF9yYXcgPSBzdHIocmVxLmdldCgidGFyZ2V0X3JlbGF0aXZlX3BhdGgiKSBvciAiIikKICAgICAgICB0YXJnZXQsIHRhcmdldF9yZWwgPSBzYWZlX3JlbChWQVVMVCwgdGFyZ2V0X3JhdywgbXVzdF9leGlzdD1UcnVlKQogICAgICAgIHJlcXVpcmVfbWQodGFyZ2V0X3JlbCkKICAgICAgICBpZiB0YXJnZXQuaXNfc3ltbGluaygpOgogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6InN5bWxpbmtfdGFyZ2V0X3JlamVjdGVkIn0sIDMwKQoKICAgICAgICBuZXdfdGV4dCA9IHJlcS5nZXQoIm5ld19jb250ZW50IikKICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShuZXdfdGV4dCwgc3RyKToKICAgICAgICAgICAgZW1pdCh7InN0YXR1cyI6ImVycm9yIiwiZXJyb3IiOiJuZXdfY29udGVudF9yZXF1aXJlZCJ9LCAzMSkKICAgICAgICBpZiBsZW4obmV3X3RleHQpID4gTUFYX1RFWFRfQ0hBUlM6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoibmV3X2NvbnRlbnRfdG9vX2xhcmdlIiwibWF4X2NoYXJzIjpNQVhfVEVYVF9DSEFSU30sIDMyKQoKICAgICAgICBvbGRfYnl0ZXMgPSB0YXJnZXQucmVhZF9ieXRlcygpCiAgICAgICAgb2xkX3RleHQgPSByZWFkX3V0ZjgodGFyZ2V0KQogICAgICAgIG9sZF9zaGEgPSBzaGFfYnl0ZXMob2xkX2J5dGVzKQogICAgICAgIG5ld19zaGEgPSBzaGFfdGV4dChuZXdfdGV4dCkKICAgICAgICBwbGFuID0gewogICAgICAgICAgICAiYWN0aW9uIjoiZWRpdF9ub3RlIiwKICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAib3JpZ2luYWxfc2hhMjU2IjpvbGRfc2hhLAogICAgICAgICAgICAicHJvcG9zZWRfc2hhMjU2IjpuZXdfc2hhLAogICAgICAgIH0KICAgICAgICB0b2tlbiA9IHBsYW5fdG9rZW4ocGxhbikKICAgICAgICBkaWZmID0gdW5pZmllZChvbGRfdGV4dCwgbmV3X3RleHQsIGYidmF1bHQve3RhcmdldF9yZWx9IiwgZiJ2YXVsdC97dGFyZ2V0X3JlbH0iKQoKICAgICAgICBpZiBtb2RlID09ICJwcmV2aWV3IjoKICAgICAgICAgICAgZW1pdCh7CiAgICAgICAgICAgICAgICAic3RhdHVzIjoib2siLAogICAgICAgICAgICAgICAgIm1vZGUiOiJwcmV2aWV3IiwKICAgICAgICAgICAgICAgICJhY3Rpb24iOiJlZGl0X25vdGUiLAogICAgICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAgICAgIm9yaWdpbmFsX3NoYTI1NiI6b2xkX3NoYSwKICAgICAgICAgICAgICAgICJwcm9wb3NlZF9zaGEyNTYiOm5ld19zaGEsCiAgICAgICAgICAgICAgICAiYXBwcm92YWxfdG9rZW4iOnRva2VuLAogICAgICAgICAgICAgICAgImRpZmYiOmRpZmYsCiAgICAgICAgICAgICAgICAiY2hhbmdlZCI6IG9sZF9zaGEgIT0gbmV3X3NoYSwKICAgICAgICAgICAgfSkKCiAgICAgICAgaWYgYXBwcm92YWwgIT0gdG9rZW46CiAgICAgICAgICAgIGVtaXQoewogICAgICAgICAgICAgICAgInN0YXR1cyI6ImRlbmllZCIsCiAgICAgICAgICAgICAgICAiZXJyb3IiOiJhcHByb3ZhbF90b2tlbl9taXNtYXRjaCIsCiAgICAgICAgICAgICAgICAiYWN0aW9uIjoiZWRpdF9ub3RlIiwKICAgICAgICAgICAgICAgICJ0YXJnZXRfcmVsYXRpdmVfcGF0aCI6dGFyZ2V0X3JlbCwKICAgICAgICAgICAgfSwgNDApCgogICAgICAgICMgRXhhY3Qgb3B0aW1pc3RpYyBjb25jdXJyZW5jeSBndWFyZDogY3VycmVudCBmaWxlIG11c3Qgc3RpbGwgbWF0Y2ggcHJldmlldy4KICAgICAgICBjdXJyZW50X2J5dGVzID0gdGFyZ2V0LnJlYWRfYnl0ZXMoKQogICAgICAgIGlmIHNoYV9ieXRlcyhjdXJyZW50X2J5dGVzKSAhPSBvbGRfc2hhOgogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZGVuaWVkIiwiZXJyb3IiOiJ0YXJnZXRfY2hhbmdlZF9zaW5jZV9wcmV2aWV3In0sIDQxKQoKICAgICAgICByZWNvdmVyeV9pZCwgcmVjb3ZlcnlfZmlsZSA9IHJlY292ZXJ5X3NuYXBzaG90KAogICAgICAgICAgICBhY3Rpb249ImVkaXRfbm90ZSIsCiAgICAgICAgICAgIHRhcmdldF9yZWw9dGFyZ2V0X3JlbCwKICAgICAgICAgICAgc291cmNlX2J5dGVzPWN1cnJlbnRfYnl0ZXMsCiAgICAgICAgICAgIGV4dHJhPXsicHJvcG9zZWRfc2hhMjU2IjpuZXdfc2hhfSwKICAgICAgICApCgogICAgICAgIHRtcCA9IHRhcmdldC5wYXJlbnQgLyBmIi57dGFyZ2V0Lm5hbWV9Lm9yaW9uLXt1dWlkNCgpLmhleFs6OF19LnRtcCIKICAgICAgICB0bXAud3JpdGVfdGV4dChuZXdfdGV4dCwgZW5jb2Rpbmc9InV0Zi04IiwgbmV3bGluZT0iXG4iKQogICAgICAgIG9zLnJlcGxhY2UodG1wLCB0YXJnZXQpCgogICAgICAgIHJlc3VsdF9zaGEgPSBzaGFfYnl0ZXModGFyZ2V0LnJlYWRfYnl0ZXMoKSkKICAgICAgICBpZiByZXN1bHRfc2hhICE9IG5ld19zaGE6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoicG9zdF93cml0ZV9oYXNoX21pc21hdGNoIn0sIDQyKQoKICAgICAgICBlbWl0KHsKICAgICAgICAgICAgInN0YXR1cyI6Im9rIiwKICAgICAgICAgICAgIm1vZGUiOiJhcHBseSIsCiAgICAgICAgICAgICJhY3Rpb24iOiJlZGl0X25vdGUiLAogICAgICAgICAgICAidGFyZ2V0X3JlbGF0aXZlX3BhdGgiOnRhcmdldF9yZWwsCiAgICAgICAgICAgICJvcmlnaW5hbF9zaGEyNTYiOm9sZF9zaGEsCiAgICAgICAgICAgICJyZXN1bHRfc2hhMjU2IjpyZXN1bHRfc2hhLAogICAgICAgICAgICAicmVjb3ZlcnlfaWQiOnJlY292ZXJ5X2lkLAogICAgICAgICAgICAicmVjb3ZlcnlfZmlsZSI6cmVjb3ZlcnlfZmlsZSwKICAgICAgICB9KQoKICAgIGVsc2U6ICAjIHJlc3RvcmUKICAgICAgICB0YXJnZXRfcmF3ID0gc3RyKHJlcS5nZXQoInRhcmdldF9yZWxhdGl2ZV9wYXRoIikgb3IgIiIpCiAgICAgICAgcmVjb3ZlcnlfcmF3ID0gc3RyKHJlcS5nZXQoInJlY292ZXJ5X2ZpbGUiKSBvciAiIikKICAgICAgICB0YXJnZXQsIHRhcmdldF9yZWwgPSBzYWZlX3JlbChWQVVMVCwgdGFyZ2V0X3JhdywgbXVzdF9leGlzdD1UcnVlKQogICAgICAgIHJlY292ZXJ5LCByZWNvdmVyeV9yZWwgPSBzYWZlX3JlbChSRUNPVkVSWSwgcmVjb3ZlcnlfcmF3LCBtdXN0X2V4aXN0PVRydWUpCiAgICAgICAgcmVxdWlyZV9tZCh0YXJnZXRfcmVsKQogICAgICAgIHJlcXVpcmVfbWQocmVjb3ZlcnlfcmVsKQogICAgICAgIGlmIHRhcmdldC5pc19zeW1saW5rKCkgb3IgcmVjb3ZlcnkuaXNfc3ltbGluaygpOgogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZXJyb3IiLCJlcnJvciI6InN5bWxpbmtfcmVzdG9yZV9yZWplY3RlZCJ9LCA1MCkKCiAgICAgICAgY3VycmVudF9ieXRlcyA9IHRhcmdldC5yZWFkX2J5dGVzKCkKICAgICAgICBiYWNrdXBfYnl0ZXMgPSByZWNvdmVyeS5yZWFkX2J5dGVzKCkKICAgICAgICBjdXJyZW50X3RleHQgPSByZWFkX3V0ZjgodGFyZ2V0KQogICAgICAgIGJhY2t1cF90ZXh0ID0gcmVhZF91dGY4KHJlY292ZXJ5KQogICAgICAgIGN1cnJlbnRfc2hhID0gc2hhX2J5dGVzKGN1cnJlbnRfYnl0ZXMpCiAgICAgICAgYmFja3VwX3NoYSA9IHNoYV9ieXRlcyhiYWNrdXBfYnl0ZXMpCgogICAgICAgIHBsYW4gPSB7CiAgICAgICAgICAgICJhY3Rpb24iOiJyZXN0b3JlIiwKICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAicmVjb3ZlcnlfZmlsZSI6cmVjb3ZlcnlfcmVsLAogICAgICAgICAgICAiY3VycmVudF9zaGEyNTYiOmN1cnJlbnRfc2hhLAogICAgICAgICAgICAicmVzdG9yZV9zaGEyNTYiOmJhY2t1cF9zaGEsCiAgICAgICAgfQogICAgICAgIHRva2VuID0gcGxhbl90b2tlbihwbGFuKQogICAgICAgIGRpZmYgPSB1bmlmaWVkKGN1cnJlbnRfdGV4dCwgYmFja3VwX3RleHQsIGYidmF1bHQve3RhcmdldF9yZWx9IiwgZiJyZWNvdmVyeS97cmVjb3ZlcnlfcmVsfSIpCgogICAgICAgIGlmIG1vZGUgPT0gInByZXZpZXciOgogICAgICAgICAgICBlbWl0KHsKICAgICAgICAgICAgICAgICJzdGF0dXMiOiJvayIsCiAgICAgICAgICAgICAgICAibW9kZSI6InByZXZpZXciLAogICAgICAgICAgICAgICAgImFjdGlvbiI6InJlc3RvcmUiLAogICAgICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAgICAgInJlY292ZXJ5X2ZpbGUiOnJlY292ZXJ5X3JlbCwKICAgICAgICAgICAgICAgICJjdXJyZW50X3NoYTI1NiI6Y3VycmVudF9zaGEsCiAgICAgICAgICAgICAgICAicmVzdG9yZV9zaGEyNTYiOmJhY2t1cF9zaGEsCiAgICAgICAgICAgICAgICAiYXBwcm92YWxfdG9rZW4iOnRva2VuLAogICAgICAgICAgICAgICAgImRpZmYiOmRpZmYsCiAgICAgICAgICAgIH0pCgogICAgICAgIGlmIGFwcHJvdmFsICE9IHRva2VuOgogICAgICAgICAgICBlbWl0KHsic3RhdHVzIjoiZGVuaWVkIiwiZXJyb3IiOiJhcHByb3ZhbF90b2tlbl9taXNtYXRjaCIsImFjdGlvbiI6InJlc3RvcmUifSwgNjApCgogICAgICAgIGlmIHNoYV9ieXRlcyh0YXJnZXQucmVhZF9ieXRlcygpKSAhPSBjdXJyZW50X3NoYToKICAgICAgICAgICAgZW1pdCh7InN0YXR1cyI6ImRlbmllZCIsImVycm9yIjoidGFyZ2V0X2NoYW5nZWRfc2luY2VfcHJldmlldyJ9LCA2MSkKCiAgICAgICAgIyBQcmVzZXJ2ZSB0aGUgY3VycmVudCBzdGF0ZSBiZWZvcmUgcmVzdG9yZSBzbyByb2xsYmFjayBpdHNlbGYgaXMgcmV2ZXJzaWJsZS4KICAgICAgICByZWNvdmVyeV9pZCwgcmVjb3ZlcnlfZmlsZTIgPSByZWNvdmVyeV9zbmFwc2hvdCgKICAgICAgICAgICAgYWN0aW9uPSJyZXN0b3JlIiwKICAgICAgICAgICAgdGFyZ2V0X3JlbD10YXJnZXRfcmVsLAogICAgICAgICAgICBzb3VyY2VfYnl0ZXM9Y3VycmVudF9ieXRlcywKICAgICAgICAgICAgZXh0cmE9eyJyZXN0b3JlZF9mcm9tIjpyZWNvdmVyeV9yZWx9LAogICAgICAgICkKCiAgICAgICAgdG1wID0gdGFyZ2V0LnBhcmVudCAvIGYiLnt0YXJnZXQubmFtZX0ub3Jpb24tcmVzdG9yZS17dXVpZDQoKS5oZXhbOjhdfS50bXAiCiAgICAgICAgdG1wLndyaXRlX2J5dGVzKGJhY2t1cF9ieXRlcykKICAgICAgICBvcy5yZXBsYWNlKHRtcCwgdGFyZ2V0KQogICAgICAgIHJlc3VsdF9zaGEgPSBzaGFfYnl0ZXModGFyZ2V0LnJlYWRfYnl0ZXMoKSkKICAgICAgICBpZiByZXN1bHRfc2hhICE9IGJhY2t1cF9zaGE6CiAgICAgICAgICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoicmVzdG9yZV9oYXNoX21pc21hdGNoIn0sIDYyKQoKICAgICAgICBlbWl0KHsKICAgICAgICAgICAgInN0YXR1cyI6Im9rIiwKICAgICAgICAgICAgIm1vZGUiOiJhcHBseSIsCiAgICAgICAgICAgICJhY3Rpb24iOiJyZXN0b3JlIiwKICAgICAgICAgICAgInRhcmdldF9yZWxhdGl2ZV9wYXRoIjp0YXJnZXRfcmVsLAogICAgICAgICAgICAicmVzdWx0X3NoYTI1NiI6cmVzdWx0X3NoYSwKICAgICAgICAgICAgInJlY292ZXJ5X2lkIjpyZWNvdmVyeV9pZCwKICAgICAgICAgICAgInJlY292ZXJ5X2ZpbGUiOnJlY292ZXJ5X2ZpbGUyLAogICAgICAgIH0pCgpleGNlcHQgRmlsZU5vdEZvdW5kRXJyb3IgYXMgZXhjOgogICAgZW1pdCh7InN0YXR1cyI6ImVycm9yIiwiZXJyb3IiOnN0cihleGMpfSwgNzApCmV4Y2VwdCBWYWx1ZUVycm9yIGFzIGV4YzoKICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjpzdHIoZXhjKX0sIDcxKQpleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgIGVtaXQoeyJzdGF0dXMiOiJlcnJvciIsImVycm9yIjoiYnJva2VyX2V4Y2VwdGlvbiIsImRldGFpbCI6ZiJ7dHlwZShleGMpLl9fbmFtZV9ffToge3N0cihleGMpWzoyMDBdfSJ9LCA5OSkK"

function Invoke-BrokerRequest {
    param([Parameter(Mandatory = $true)][hashtable]$Request)

    $requestJson = $Request | ConvertTo-Json -Compress -Depth 8
    $loader = "import base64; exec(base64.b64decode('$Payload'))"

    $raw = $requestJson | & docker exec -i `
        -u 10000:10000 `
        $Container `
        /opt/iai/venv/bin/python -c $loader 2>&1

    $code = $LASTEXITCODE
    $text = (($raw | ForEach-Object { [string]$_ }) -join "`n").Trim()

    if ([string]::IsNullOrWhiteSpace($text)) {
        throw "Vault broker returned no output."
    }

    try {
        $obj = $text | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        throw ("Vault broker returned non-JSON output (exit {0}): {1}" -f $code, $text)
    }

    return [pscustomobject]@{
        ExitCode = $code
        Object = $obj
    }
}

$running = @(& docker ps --format "{{.Names}}")
if ($LASTEXITCODE -ne 0) {
    throw "Could not list running Docker containers."
}
if ($running -notcontains $Container) {
    throw "Controlled vault broker '$Container' is not running."
}

$request = @{
    action = $Action.ToLowerInvariant() -replace "draft","_draft" -replace "note","_note"
    mode = $Mode.ToLowerInvariant()
}

if ($Action -eq "MoveDraft") {
    if ([string]::IsNullOrWhiteSpace($SourceDraft) -or [string]::IsNullOrWhiteSpace($TargetRelativePath)) {
        throw "MoveDraft requires -SourceDraft and -TargetRelativePath."
    }
    $request.action = "move_draft"
    $request.source_draft = $SourceDraft
    $request.target_relative_path = $TargetRelativePath
}
elseif ($Action -eq "EditNote") {
    if ([string]::IsNullOrWhiteSpace($TargetRelativePath)) {
        throw "EditNote requires -TargetRelativePath."
    }
    if (-not [string]::IsNullOrWhiteSpace($NewContentFile)) {
        if (-not (Test-Path -LiteralPath $NewContentFile -PathType Leaf)) {
            throw "New content file not found: $NewContentFile"
        }
        $NewContent = Get-Content -LiteralPath $NewContentFile -Raw
    }
    if ($null -eq $NewContent) {
        throw "EditNote requires -NewContent or -NewContentFile."
    }
    $request.action = "edit_note"
    $request.target_relative_path = $TargetRelativePath
    $request.new_content = $NewContent
}
else {
    if ([string]::IsNullOrWhiteSpace($TargetRelativePath) -or [string]::IsNullOrWhiteSpace($RecoveryFile)) {
        throw "Restore requires -TargetRelativePath and -RecoveryFile."
    }
    $request.action = "restore"
    $request.target_relative_path = $TargetRelativePath
    $request.recovery_file = $RecoveryFile
}

if ($Mode -eq "Apply") {
    if ([string]::IsNullOrWhiteSpace($ApprovalToken)) {
        throw "Apply requires the exact -ApprovalToken returned by Preview."
    }
    $request.approval_token = $ApprovalToken
}

$result = Invoke-BrokerRequest -Request $request

# A policy denial is an expected broker outcome, not a broker failure.
# Handle it before generic non-zero-exit handling so callers can verify
# denied-action no-op behavior without receiving a PowerShell exception.
if ($result.Object.status -eq "denied") {
    if ($Json) {
        $result.Object | ConvertTo-Json -Depth 8
        exit 20
    }
    Write-Host "ORION_VAULT_BROKER=DENIED"
    Write-Host ("REASON={0}" -f $result.Object.error)
    exit 20
}

if ($result.ExitCode -ne 0 -or $result.Object.status -ne "ok") {
    throw ("Vault broker failed: {0}" -f ($result.Object | ConvertTo-Json -Compress -Depth 8))
}

if ($Json) {
    $result.Object | ConvertTo-Json -Depth 8
    exit 0
}

if ($Mode -eq "Preview") {
    Write-Host "ORION_VAULT_BROKER_PREVIEW=PASS"
    Write-Host ("ACTION={0}" -f $result.Object.action)
    if ($result.Object.source_draft) {
        Write-Host ("SOURCE_DRAFT={0}" -f $result.Object.source_draft)
    }
    if ($result.Object.target_relative_path) {
        Write-Host ("TARGET_RELATIVE_PATH={0}" -f $result.Object.target_relative_path)
    }
    if ($result.Object.recovery_file) {
        Write-Host ("RECOVERY_FILE={0}" -f $result.Object.recovery_file)
    }
    Write-Host ("APPROVAL_TOKEN={0}" -f $result.Object.approval_token)
    Write-Host ""
    Write-Host "--- DIFF BEGIN ---"
    Write-Output ([string]$result.Object.diff)
    Write-Host "--- DIFF END ---"
}
else {
    Write-Host "ORION_VAULT_BROKER_APPLY=PASS"
    Write-Host ("ACTION={0}" -f $result.Object.action)
    if ($result.Object.target_relative_path) {
        Write-Host ("TARGET_RELATIVE_PATH={0}" -f $result.Object.target_relative_path)
    }
    if ($result.Object.result_sha256) {
        Write-Host ("RESULT_SHA256={0}" -f $result.Object.result_sha256)
    }
    if ($result.Object.recovery_id) {
        Write-Host ("RECOVERY_ID={0}" -f $result.Object.recovery_id)
        Write-Host ("RECOVERY_FILE={0}" -f $result.Object.recovery_file)
    }
}
